[package]
name = "ion-proc"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
quote = "1.0.21"
prettyplease = "0.1.19"
proc-macro2 = "1.0.46"
syn = { version = "1.0.101", features = ["extra-traits", "full", "visit-mut"] }

[lib]
proc-macro = true
test = false
doctest = false
